# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops
strategy:
  matrix:
#    linux:
#      imageName: 'ubuntu-16.04'
#    mac:
#      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- powershell: |
    Invoke-WebRequest -Uri "https://rakudo.org/dl/star/rakudo-star-2020.01.tar.gz" -OutFile "rakudo-star-2020.01.tar.gz"

- script: |
    dir /s 
    
- script: |
    choco install wixtoolset 

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'rakudo-star-2020.01.tar.gz' 

- script: |
    dir /s   

- script: date /t
  displayName: Get the date
  
- script: dir
  workingDirectory: $(Agent.BuildDirectory)
  displayName: List contents of a folder
  
- script: |
    set MYVAR=foo
    set
  displayName: Set a variable and then display all
  env:
    aVarFromYaml: someValue

- script: perl -v
- script: perl -V
