# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops

variables:
  star-year: 2020
  star-month: 01
  star-name: rakudo-star
  star-fullname: $(star-name)-$(star-year).$(star-month)
  star-tgz: $(star-fullname).tar.gz
  star-src: https://rakudo.org/dl/star/$(star-tgz)
  builddir: $(Build.SourcesDirectory)\builddir

strategy:
  matrix:
#    linux:
#      imageName: 'ubuntu-16.04'
#    mac:
#      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- script: |
    echo $(builddir)
    mkdir $(builddir)
    cd $(builddir)
    
- script: |
    which perl
    perl -v
    perl -V    

- script: |
    which tar
    which wget

- powershell: |
    Invoke-WebRequest -Uri "$(star-src)" -OutFile "$(builddir)/$(star-tgz)"

- script: dir /s 

- script: tar -xvzf "$(builddir)/$(star-tgz)" -C "$(builddir)/$(star-name)"

#- task: ExtractFiles@1
#  inputs:
#    archiveFilePatterns: "$(builddir)/$(star-tgz)"
#    destinationFolder: "$(builddir)/$(star-name)"
#    cleanDestinationFolder: false

- script: dir /s   

- script: date /t
  displayName: Get the date
  
- script: dir
  workingDirectory: $(Agent.BuildDirectory)
  displayName: List contents of a folder
  
- script: |
    set MYVAR=foo
    set
  displayName: Set a variable and then display all
  env:
    aVarFromYaml: someValue

